// Données des capitales : une entrée par pays. Module pur : aucun accès au DOM, importable par la page et par node.
//
// Périmètre : les 193 États membres de l'ONU et les 2 États observateurs (Vatican, Palestine), soit 195 entrées.
// Taïwan et le Kosovo n'y sont pas (liste ONU stricte), ni les territoires dépendants (Groenland, Porto Rico…).
//
// Règle de la capitale retenue :
// - la capitale officielle, celle que fixe la constitution ou la loi ;
// - si le pays en a plusieurs, la capitale officielle va dans « capitale » et les autres sièges du pouvoir
//   (gouvernement, parlement, justice) dans « autresCapitales » ;
// - capitale disputée : Palestine, Ramallah, siège effectif de ses institutions (Jérusalem-Est, revendiquée,
//   en autre capitale) ; Israël, Jérusalem, capitale qu'il déclare. Indonésie : Jakarta, tant que le transfert
//   vers Nusantara n'est pas effectif.
// Dans tous ces cas, les capitales d'un même pays partagent le fuseau, sauf Nusantara : le choix ne change donc
// pas l'heure affichée.
//
// Continents : liste fermée CONTINENTS ci-dessous. Amérique centrale et Caraïbes comptent en Amérique du Nord.
// Un pays à cheval sur deux continents est rangé selon sa capitale : Russie en Europe (Moscou), Turquie en Asie
// (Ankara), Égypte en Afrique ; Chypre, Arménie, Géorgie, Azerbaïdjan et Kazakhstan en Asie.
//
// Fuseau : le fuseau IANA de la capitale (ex. « Europe/Paris »), celui qu'attend Intl.DateTimeFormat.

export const CONTINENTS = Object.freeze([
  'Afrique',
  'Amérique du Nord',
  'Amérique du Sud',
  'Asie',
  'Europe',
  'Océanie',
]);

const capitales = [
  // Afrique (54)
  { pays: 'Afrique du Sud', capitale: 'Pretoria', continent: 'Afrique', fuseau: 'Africa/Johannesburg', autresCapitales: ['Le Cap', 'Bloemfontein'] },
  { pays: 'Algérie', capitale: 'Alger', continent: 'Afrique', fuseau: 'Africa/Algiers' },
  { pays: 'Angola', capitale: 'Luanda', continent: 'Afrique', fuseau: 'Africa/Luanda' },
  { pays: 'Bénin', capitale: 'Porto-Novo', continent: 'Afrique', fuseau: 'Africa/Porto-Novo', autresCapitales: ['Cotonou'] },
  { pays: 'Botswana', capitale: 'Gaborone', continent: 'Afrique', fuseau: 'Africa/Gaborone' },
  { pays: 'Burkina Faso', capitale: 'Ouagadougou', continent: 'Afrique', fuseau: 'Africa/Ouagadougou' },
  { pays: 'Burundi', capitale: 'Gitega', continent: 'Afrique', fuseau: 'Africa/Bujumbura', autresCapitales: ['Bujumbura'] },
  { pays: 'Cap-Vert', capitale: 'Praia', continent: 'Afrique', fuseau: 'Atlantic/Cape_Verde' },
  { pays: 'Cameroun', capitale: 'Yaoundé', continent: 'Afrique', fuseau: 'Africa/Douala' },
  { pays: 'Centrafrique', capitale: 'Bangui', continent: 'Afrique', fuseau: 'Africa/Bangui' },
  { pays: 'Comores', capitale: 'Moroni', continent: 'Afrique', fuseau: 'Indian/Comoro' },
  { pays: 'Congo', capitale: 'Brazzaville', continent: 'Afrique', fuseau: 'Africa/Brazzaville' },
  { pays: 'République démocratique du Congo', capitale: 'Kinshasa', continent: 'Afrique', fuseau: 'Africa/Kinshasa' },
  { pays: "Côte d'Ivoire", capitale: 'Yamoussoukro', continent: 'Afrique', fuseau: 'Africa/Abidjan', autresCapitales: ['Abidjan'] },
  { pays: 'Djibouti', capitale: 'Djibouti', continent: 'Afrique', fuseau: 'Africa/Djibouti' },
  { pays: 'Égypte', capitale: 'Le Caire', continent: 'Afrique', fuseau: 'Africa/Cairo' },
  { pays: 'Érythrée', capitale: 'Asmara', continent: 'Afrique', fuseau: 'Africa/Asmara' },
  { pays: 'Eswatini', capitale: 'Mbabane', continent: 'Afrique', fuseau: 'Africa/Mbabane', autresCapitales: ['Lobamba'] },
  { pays: 'Éthiopie', capitale: 'Addis-Abeba', continent: 'Afrique', fuseau: 'Africa/Addis_Ababa' },
  { pays: 'Gabon', capitale: 'Libreville', continent: 'Afrique', fuseau: 'Africa/Libreville' },
  { pays: 'Gambie', capitale: 'Banjul', continent: 'Afrique', fuseau: 'Africa/Banjul' },
  { pays: 'Ghana', capitale: 'Accra', continent: 'Afrique', fuseau: 'Africa/Accra' },
  { pays: 'Guinée', capitale: 'Conakry', continent: 'Afrique', fuseau: 'Africa/Conakry' },
  { pays: 'Guinée-Bissau', capitale: 'Bissau', continent: 'Afrique', fuseau: 'Africa/Bissau' },
  { pays: 'Guinée équatoriale', capitale: 'Malabo', continent: 'Afrique', fuseau: 'Africa/Malabo' },
  { pays: 'Kenya', capitale: 'Nairobi', continent: 'Afrique', fuseau: 'Africa/Nairobi' },
  { pays: 'Lesotho', capitale: 'Maseru', continent: 'Afrique', fuseau: 'Africa/Maseru' },
  { pays: 'Liberia', capitale: 'Monrovia', continent: 'Afrique', fuseau: 'Africa/Monrovia' },
  { pays: 'Libye', capitale: 'Tripoli', continent: 'Afrique', fuseau: 'Africa/Tripoli' },
  { pays: 'Madagascar', capitale: 'Antananarivo', continent: 'Afrique', fuseau: 'Indian/Antananarivo' },
  { pays: 'Malawi', capitale: 'Lilongwe', continent: 'Afrique', fuseau: 'Africa/Blantyre' },
  { pays: 'Mali', capitale: 'Bamako', continent: 'Afrique', fuseau: 'Africa/Bamako' },
  { pays: 'Maroc', capitale: 'Rabat', continent: 'Afrique', fuseau: 'Africa/Casablanca' },
  { pays: 'Maurice', capitale: 'Port-Louis', continent: 'Afrique', fuseau: 'Indian/Mauritius' },
  { pays: 'Mauritanie', capitale: 'Nouakchott', continent: 'Afrique', fuseau: 'Africa/Nouakchott' },
  { pays: 'Mozambique', capitale: 'Maputo', continent: 'Afrique', fuseau: 'Africa/Maputo' },
  { pays: 'Namibie', capitale: 'Windhoek', continent: 'Afrique', fuseau: 'Africa/Windhoek' },
  { pays: 'Niger', capitale: 'Niamey', continent: 'Afrique', fuseau: 'Africa/Niamey' },
  { pays: 'Nigeria', capitale: 'Abuja', continent: 'Afrique', fuseau: 'Africa/Lagos' },
  { pays: 'Ouganda', capitale: 'Kampala', continent: 'Afrique', fuseau: 'Africa/Kampala' },
  { pays: 'Rwanda', capitale: 'Kigali', continent: 'Afrique', fuseau: 'Africa/Kigali' },
  { pays: 'Sao Tomé-et-Principe', capitale: 'São Tomé', continent: 'Afrique', fuseau: 'Africa/Sao_Tome' },
  { pays: 'Sénégal', capitale: 'Dakar', continent: 'Afrique', fuseau: 'Africa/Dakar' },
  { pays: 'Seychelles', capitale: 'Victoria', continent: 'Afrique', fuseau: 'Indian/Mahe' },
  { pays: 'Sierra Leone', capitale: 'Freetown', continent: 'Afrique', fuseau: 'Africa/Freetown' },
  { pays: 'Somalie', capitale: 'Mogadiscio', continent: 'Afrique', fuseau: 'Africa/Mogadishu' },
  { pays: 'Soudan', capitale: 'Khartoum', continent: 'Afrique', fuseau: 'Africa/Khartoum' },
  { pays: 'Soudan du Sud', capitale: 'Djouba', continent: 'Afrique', fuseau: 'Africa/Juba' },
  { pays: 'Tanzanie', capitale: 'Dodoma', continent: 'Afrique', fuseau: 'Africa/Dar_es_Salaam', autresCapitales: ['Dar es Salam'] },
  { pays: 'Tchad', capitale: "N'Djaména", continent: 'Afrique', fuseau: 'Africa/Ndjamena' },
  { pays: 'Togo', capitale: 'Lomé', continent: 'Afrique', fuseau: 'Africa/Lome' },
  { pays: 'Tunisie', capitale: 'Tunis', continent: 'Afrique', fuseau: 'Africa/Tunis' },
  { pays: 'Zambie', capitale: 'Lusaka', continent: 'Afrique', fuseau: 'Africa/Lusaka' },
  { pays: 'Zimbabwe', capitale: 'Harare', continent: 'Afrique', fuseau: 'Africa/Harare' },

  // Amérique du Nord, Amérique centrale et Caraïbes (23)
  { pays: 'Antigua-et-Barbuda', capitale: "Saint John's", continent: 'Amérique du Nord', fuseau: 'America/Antigua' },
  { pays: 'Bahamas', capitale: 'Nassau', continent: 'Amérique du Nord', fuseau: 'America/Nassau' },
  { pays: 'Barbade', capitale: 'Bridgetown', continent: 'Amérique du Nord', fuseau: 'America/Barbados' },
  { pays: 'Belize', capitale: 'Belmopan', continent: 'Amérique du Nord', fuseau: 'America/Belize' },
  { pays: 'Canada', capitale: 'Ottawa', continent: 'Amérique du Nord', fuseau: 'America/Toronto' },
  { pays: 'Costa Rica', capitale: 'San José', continent: 'Amérique du Nord', fuseau: 'America/Costa_Rica' },
  { pays: 'Cuba', capitale: 'La Havane', continent: 'Amérique du Nord', fuseau: 'America/Havana' },
  { pays: 'Dominique', capitale: 'Roseau', continent: 'Amérique du Nord', fuseau: 'America/Dominica' },
  { pays: 'États-Unis', capitale: 'Washington', continent: 'Amérique du Nord', fuseau: 'America/New_York' },
  { pays: 'Grenade', capitale: 'Saint-Georges', continent: 'Amérique du Nord', fuseau: 'America/Grenada' },
  { pays: 'Guatemala', capitale: 'Guatemala', continent: 'Amérique du Nord', fuseau: 'America/Guatemala' },
  { pays: 'Haïti', capitale: 'Port-au-Prince', continent: 'Amérique du Nord', fuseau: 'America/Port-au-Prince' },
  { pays: 'Honduras', capitale: 'Tegucigalpa', continent: 'Amérique du Nord', fuseau: 'America/Tegucigalpa' },
  { pays: 'Jamaïque', capitale: 'Kingston', continent: 'Amérique du Nord', fuseau: 'America/Jamaica' },
  { pays: 'Mexique', capitale: 'Mexico', continent: 'Amérique du Nord', fuseau: 'America/Mexico_City' },
  { pays: 'Nicaragua', capitale: 'Managua', continent: 'Amérique du Nord', fuseau: 'America/Managua' },
  { pays: 'Panama', capitale: 'Panama', continent: 'Amérique du Nord', fuseau: 'America/Panama' },
  { pays: 'République dominicaine', capitale: 'Saint-Domingue', continent: 'Amérique du Nord', fuseau: 'America/Santo_Domingo' },
  { pays: 'Saint-Christophe-et-Niévès', capitale: 'Basseterre', continent: 'Amérique du Nord', fuseau: 'America/St_Kitts' },
  { pays: 'Sainte-Lucie', capitale: 'Castries', continent: 'Amérique du Nord', fuseau: 'America/St_Lucia' },
  { pays: 'Saint-Vincent-et-les-Grenadines', capitale: 'Kingstown', continent: 'Amérique du Nord', fuseau: 'America/St_Vincent' },
  { pays: 'Salvador', capitale: 'San Salvador', continent: 'Amérique du Nord', fuseau: 'America/El_Salvador' },
  { pays: 'Trinité-et-Tobago', capitale: "Port-d'Espagne", continent: 'Amérique du Nord', fuseau: 'America/Port_of_Spain' },

  // Amérique du Sud (12)
  { pays: 'Argentine', capitale: 'Buenos Aires', continent: 'Amérique du Sud', fuseau: 'America/Argentina/Buenos_Aires' },
  { pays: 'Bolivie', capitale: 'Sucre', continent: 'Amérique du Sud', fuseau: 'America/La_Paz', autresCapitales: ['La Paz'] },
  { pays: 'Brésil', capitale: 'Brasilia', continent: 'Amérique du Sud', fuseau: 'America/Sao_Paulo' },
  { pays: 'Chili', capitale: 'Santiago', continent: 'Amérique du Sud', fuseau: 'America/Santiago' },
  { pays: 'Colombie', capitale: 'Bogota', continent: 'Amérique du Sud', fuseau: 'America/Bogota' },
  { pays: 'Équateur', capitale: 'Quito', continent: 'Amérique du Sud', fuseau: 'America/Guayaquil' },
  { pays: 'Guyana', capitale: 'Georgetown', continent: 'Amérique du Sud', fuseau: 'America/Guyana' },
  { pays: 'Paraguay', capitale: 'Asuncion', continent: 'Amérique du Sud', fuseau: 'America/Asuncion' },
  { pays: 'Pérou', capitale: 'Lima', continent: 'Amérique du Sud', fuseau: 'America/Lima' },
  { pays: 'Suriname', capitale: 'Paramaribo', continent: 'Amérique du Sud', fuseau: 'America/Paramaribo' },
  { pays: 'Uruguay', capitale: 'Montevideo', continent: 'Amérique du Sud', fuseau: 'America/Montevideo' },
  { pays: 'Venezuela', capitale: 'Caracas', continent: 'Amérique du Sud', fuseau: 'America/Caracas' },

  // Asie (48)
  { pays: 'Afghanistan', capitale: 'Kaboul', continent: 'Asie', fuseau: 'Asia/Kabul' },
  { pays: 'Arabie saoudite', capitale: 'Riyad', continent: 'Asie', fuseau: 'Asia/Riyadh' },
  { pays: 'Arménie', capitale: 'Erevan', continent: 'Asie', fuseau: 'Asia/Yerevan' },
  { pays: 'Azerbaïdjan', capitale: 'Bakou', continent: 'Asie', fuseau: 'Asia/Baku' },
  { pays: 'Bahreïn', capitale: 'Manama', continent: 'Asie', fuseau: 'Asia/Bahrain' },
  { pays: 'Bangladesh', capitale: 'Dacca', continent: 'Asie', fuseau: 'Asia/Dhaka' },
  { pays: 'Bhoutan', capitale: 'Thimphou', continent: 'Asie', fuseau: 'Asia/Thimphu' },
  { pays: 'Birmanie', capitale: 'Naypyidaw', continent: 'Asie', fuseau: 'Asia/Yangon' },
  { pays: 'Brunei', capitale: 'Bandar Seri Begawan', continent: 'Asie', fuseau: 'Asia/Brunei' },
  { pays: 'Cambodge', capitale: 'Phnom Penh', continent: 'Asie', fuseau: 'Asia/Phnom_Penh' },
  { pays: 'Chine', capitale: 'Pékin', continent: 'Asie', fuseau: 'Asia/Shanghai' },
  { pays: 'Chypre', capitale: 'Nicosie', continent: 'Asie', fuseau: 'Asia/Nicosia' },
  { pays: 'Corée du Nord', capitale: 'Pyongyang', continent: 'Asie', fuseau: 'Asia/Pyongyang' },
  { pays: 'Corée du Sud', capitale: 'Séoul', continent: 'Asie', fuseau: 'Asia/Seoul' },
  { pays: 'Émirats arabes unis', capitale: 'Abou Dabi', continent: 'Asie', fuseau: 'Asia/Dubai' },
  { pays: 'Géorgie', capitale: 'Tbilissi', continent: 'Asie', fuseau: 'Asia/Tbilisi' },
  { pays: 'Inde', capitale: 'New Delhi', continent: 'Asie', fuseau: 'Asia/Kolkata' },
  { pays: 'Indonésie', capitale: 'Jakarta', continent: 'Asie', fuseau: 'Asia/Jakarta' },
  { pays: 'Irak', capitale: 'Bagdad', continent: 'Asie', fuseau: 'Asia/Baghdad' },
  { pays: 'Iran', capitale: 'Téhéran', continent: 'Asie', fuseau: 'Asia/Tehran' },
  { pays: 'Israël', capitale: 'Jérusalem', continent: 'Asie', fuseau: 'Asia/Jerusalem' },
  { pays: 'Japon', capitale: 'Tokyo', continent: 'Asie', fuseau: 'Asia/Tokyo' },
  { pays: 'Jordanie', capitale: 'Amman', continent: 'Asie', fuseau: 'Asia/Amman' },
  { pays: 'Kazakhstan', capitale: 'Astana', continent: 'Asie', fuseau: 'Asia/Almaty' },
  { pays: 'Kirghizistan', capitale: 'Bichkek', continent: 'Asie', fuseau: 'Asia/Bishkek' },
  { pays: 'Koweït', capitale: 'Koweït', continent: 'Asie', fuseau: 'Asia/Kuwait' },
  { pays: 'Laos', capitale: 'Vientiane', continent: 'Asie', fuseau: 'Asia/Vientiane' },
  { pays: 'Liban', capitale: 'Beyrouth', continent: 'Asie', fuseau: 'Asia/Beirut' },
  { pays: 'Malaisie', capitale: 'Kuala Lumpur', continent: 'Asie', fuseau: 'Asia/Kuala_Lumpur', autresCapitales: ['Putrajaya'] },
  { pays: 'Maldives', capitale: 'Malé', continent: 'Asie', fuseau: 'Indian/Maldives' },
  { pays: 'Mongolie', capitale: 'Oulan-Bator', continent: 'Asie', fuseau: 'Asia/Ulaanbaatar' },
  { pays: 'Népal', capitale: 'Katmandou', continent: 'Asie', fuseau: 'Asia/Kathmandu' },
  { pays: 'Oman', capitale: 'Mascate', continent: 'Asie', fuseau: 'Asia/Muscat' },
  { pays: 'Ouzbékistan', capitale: 'Tachkent', continent: 'Asie', fuseau: 'Asia/Tashkent' },
  { pays: 'Pakistan', capitale: 'Islamabad', continent: 'Asie', fuseau: 'Asia/Karachi' },
  { pays: 'Palestine', capitale: 'Ramallah', continent: 'Asie', fuseau: 'Asia/Hebron', autresCapitales: ['Jérusalem-Est'] },
  { pays: 'Philippines', capitale: 'Manille', continent: 'Asie', fuseau: 'Asia/Manila' },
  { pays: 'Qatar', capitale: 'Doha', continent: 'Asie', fuseau: 'Asia/Qatar' },
  { pays: 'Singapour', capitale: 'Singapour', continent: 'Asie', fuseau: 'Asia/Singapore' },
  { pays: 'Sri Lanka', capitale: 'Sri Jayawardenepura Kotte', continent: 'Asie', fuseau: 'Asia/Colombo', autresCapitales: ['Colombo'] },
  { pays: 'Syrie', capitale: 'Damas', continent: 'Asie', fuseau: 'Asia/Damascus' },
  { pays: 'Tadjikistan', capitale: 'Douchanbé', continent: 'Asie', fuseau: 'Asia/Dushanbe' },
  { pays: 'Thaïlande', capitale: 'Bangkok', continent: 'Asie', fuseau: 'Asia/Bangkok' },
  { pays: 'Timor oriental', capitale: 'Dili', continent: 'Asie', fuseau: 'Asia/Dili' },
  { pays: 'Turkménistan', capitale: 'Achgabat', continent: 'Asie', fuseau: 'Asia/Ashgabat' },
  { pays: 'Turquie', capitale: 'Ankara', continent: 'Asie', fuseau: 'Europe/Istanbul' },
  { pays: 'Viêt Nam', capitale: 'Hanoï', continent: 'Asie', fuseau: 'Asia/Ho_Chi_Minh' },
  { pays: 'Yémen', capitale: 'Sanaa', continent: 'Asie', fuseau: 'Asia/Aden' },

  // Europe (44)
  { pays: 'Albanie', capitale: 'Tirana', continent: 'Europe', fuseau: 'Europe/Tirane' },
  { pays: 'Allemagne', capitale: 'Berlin', continent: 'Europe', fuseau: 'Europe/Berlin' },
  { pays: 'Andorre', capitale: 'Andorre-la-Vieille', continent: 'Europe', fuseau: 'Europe/Andorra' },
  { pays: 'Autriche', capitale: 'Vienne', continent: 'Europe', fuseau: 'Europe/Vienna' },
  { pays: 'Belgique', capitale: 'Bruxelles', continent: 'Europe', fuseau: 'Europe/Brussels' },
  { pays: 'Biélorussie', capitale: 'Minsk', continent: 'Europe', fuseau: 'Europe/Minsk' },
  { pays: 'Bosnie-Herzégovine', capitale: 'Sarajevo', continent: 'Europe', fuseau: 'Europe/Sarajevo' },
  { pays: 'Bulgarie', capitale: 'Sofia', continent: 'Europe', fuseau: 'Europe/Sofia' },
  { pays: 'Croatie', capitale: 'Zagreb', continent: 'Europe', fuseau: 'Europe/Zagreb' },
  { pays: 'Danemark', capitale: 'Copenhague', continent: 'Europe', fuseau: 'Europe/Copenhagen' },
  { pays: 'Espagne', capitale: 'Madrid', continent: 'Europe', fuseau: 'Europe/Madrid' },
  { pays: 'Estonie', capitale: 'Tallinn', continent: 'Europe', fuseau: 'Europe/Tallinn' },
  { pays: 'Finlande', capitale: 'Helsinki', continent: 'Europe', fuseau: 'Europe/Helsinki' },
  { pays: 'France', capitale: 'Paris', continent: 'Europe', fuseau: 'Europe/Paris' },
  { pays: 'Grèce', capitale: 'Athènes', continent: 'Europe', fuseau: 'Europe/Athens' },
  { pays: 'Hongrie', capitale: 'Budapest', continent: 'Europe', fuseau: 'Europe/Budapest' },
  { pays: 'Irlande', capitale: 'Dublin', continent: 'Europe', fuseau: 'Europe/Dublin' },
  { pays: 'Islande', capitale: 'Reykjavik', continent: 'Europe', fuseau: 'Atlantic/Reykjavik' },
  { pays: 'Italie', capitale: 'Rome', continent: 'Europe', fuseau: 'Europe/Rome' },
  { pays: 'Lettonie', capitale: 'Riga', continent: 'Europe', fuseau: 'Europe/Riga' },
  { pays: 'Liechtenstein', capitale: 'Vaduz', continent: 'Europe', fuseau: 'Europe/Vaduz' },
  { pays: 'Lituanie', capitale: 'Vilnius', continent: 'Europe', fuseau: 'Europe/Vilnius' },
  { pays: 'Luxembourg', capitale: 'Luxembourg', continent: 'Europe', fuseau: 'Europe/Luxembourg' },
  { pays: 'Macédoine du Nord', capitale: 'Skopje', continent: 'Europe', fuseau: 'Europe/Skopje' },
  { pays: 'Malte', capitale: 'La Valette', continent: 'Europe', fuseau: 'Europe/Malta' },
  { pays: 'Moldavie', capitale: 'Chișinău', continent: 'Europe', fuseau: 'Europe/Chisinau' },
  { pays: 'Monaco', capitale: 'Monaco', continent: 'Europe', fuseau: 'Europe/Monaco' },
  { pays: 'Monténégro', capitale: 'Podgorica', continent: 'Europe', fuseau: 'Europe/Podgorica' },
  { pays: 'Norvège', capitale: 'Oslo', continent: 'Europe', fuseau: 'Europe/Oslo' },
  { pays: 'Pays-Bas', capitale: 'Amsterdam', continent: 'Europe', fuseau: 'Europe/Amsterdam', autresCapitales: ['La Haye'] },
  { pays: 'Pologne', capitale: 'Varsovie', continent: 'Europe', fuseau: 'Europe/Warsaw' },
  { pays: 'Portugal', capitale: 'Lisbonne', continent: 'Europe', fuseau: 'Europe/Lisbon' },
  { pays: 'Roumanie', capitale: 'Bucarest', continent: 'Europe', fuseau: 'Europe/Bucharest' },
  { pays: 'Royaume-Uni', capitale: 'Londres', continent: 'Europe', fuseau: 'Europe/London' },
  { pays: 'Russie', capitale: 'Moscou', continent: 'Europe', fuseau: 'Europe/Moscow' },
  { pays: 'Saint-Marin', capitale: 'Saint-Marin', continent: 'Europe', fuseau: 'Europe/San_Marino' },
  { pays: 'Serbie', capitale: 'Belgrade', continent: 'Europe', fuseau: 'Europe/Belgrade' },
  { pays: 'Slovaquie', capitale: 'Bratislava', continent: 'Europe', fuseau: 'Europe/Bratislava' },
  { pays: 'Slovénie', capitale: 'Ljubljana', continent: 'Europe', fuseau: 'Europe/Ljubljana' },
  { pays: 'Suède', capitale: 'Stockholm', continent: 'Europe', fuseau: 'Europe/Stockholm' },
  { pays: 'Suisse', capitale: 'Berne', continent: 'Europe', fuseau: 'Europe/Zurich' },
  { pays: 'Tchéquie', capitale: 'Prague', continent: 'Europe', fuseau: 'Europe/Prague' },
  { pays: 'Ukraine', capitale: 'Kiev', continent: 'Europe', fuseau: 'Europe/Kyiv' },
  { pays: 'Vatican', capitale: 'Cité du Vatican', continent: 'Europe', fuseau: 'Europe/Vatican' },

  // Océanie (14)
  { pays: 'Australie', capitale: 'Canberra', continent: 'Océanie', fuseau: 'Australia/Sydney' },
  { pays: 'Fidji', capitale: 'Suva', continent: 'Océanie', fuseau: 'Pacific/Fiji' },
  { pays: 'Kiribati', capitale: 'Tarawa-Sud', continent: 'Océanie', fuseau: 'Pacific/Tarawa' },
  { pays: 'Îles Marshall', capitale: 'Majuro', continent: 'Océanie', fuseau: 'Pacific/Majuro' },
  { pays: 'Micronésie', capitale: 'Palikir', continent: 'Océanie', fuseau: 'Pacific/Pohnpei' },
  { pays: 'Nauru', capitale: 'Yaren', continent: 'Océanie', fuseau: 'Pacific/Nauru' },
  { pays: 'Nouvelle-Zélande', capitale: 'Wellington', continent: 'Océanie', fuseau: 'Pacific/Auckland' },
  { pays: 'Palaos', capitale: 'Ngerulmud', continent: 'Océanie', fuseau: 'Pacific/Palau' },
  { pays: 'Papouasie-Nouvelle-Guinée', capitale: 'Port Moresby', continent: 'Océanie', fuseau: 'Pacific/Port_Moresby' },
  { pays: 'Îles Salomon', capitale: 'Honiara', continent: 'Océanie', fuseau: 'Pacific/Guadalcanal' },
  { pays: 'Samoa', capitale: 'Apia', continent: 'Océanie', fuseau: 'Pacific/Apia' },
  { pays: 'Tonga', capitale: 'Nukuʻalofa', continent: 'Océanie', fuseau: 'Pacific/Tongatapu' },
  { pays: 'Tuvalu', capitale: 'Funafuti', continent: 'Océanie', fuseau: 'Pacific/Funafuti' },
  { pays: 'Vanuatu', capitale: 'Port-Vila', continent: 'Océanie', fuseau: 'Pacific/Efate' },
];

// Figées en profondeur : un module qui les lit ne peut pas les modifier par mégarde.
for (const entree of capitales) {
  if (entree.autresCapitales) Object.freeze(entree.autresCapitales);
  Object.freeze(entree);
}

export const CAPITALES = Object.freeze(capitales);
