// Données des capitales : une entrée par pays. Module pur : aucun accès au DOM, importable par la page et par node.
//
// Périmètre : les 193 États membres de l'ONU et les 2 États observateurs (Vatican, Palestine), soit 195 entrées.
// Taïwan et le Kosovo n'y sont pas (liste ONU stricte), ni les territoires dépendants (Groenland, Porto Rico…).
//
// Règle de la capitale retenue :
// - la capitale officielle, celle que fixe la constitution ou la loi ;
// - si le pays en a plusieurs, la capitale officielle va dans « capitale » et les autres sièges du pouvoir
//   (gouvernement, parlement, justice) dans « autresCapitales » ;
// - capitale disputée : Palestine, Ramallah, siège effectif de ses institutions (Jérusalem-Est, revendiquée,
//   en autre capitale) ; Israël, Jérusalem, capitale qu'il déclare. Indonésie : Jakarta, tant que le transfert
//   vers Nusantara n'est pas effectif.
// Dans tous ces cas, les capitales d'un même pays partagent le fuseau, sauf Nusantara : le choix ne change donc
// pas l'heure affichée.
//
// Continents : liste fermée CONTINENTS ci-dessous. Amérique centrale et Caraïbes comptent en Amérique du Nord.
// Un pays à cheval sur deux continents est rangé selon sa capitale : Russie en Europe (Moscou), Turquie en Asie
// (Ankara), Égypte en Afrique ; Chypre, Arménie, Géorgie, Azerbaïdjan et Kazakhstan en Asie.
//
// Fuseau : le fuseau IANA de la capitale (ex. « Europe/Paris »), celui qu'attend Intl.DateTimeFormat.
//
// Coordonnées : lat et lon de la capitale du champ « capitale » (pas des autresCapitales), en degrés décimaux
// WGS84, arrondies à 2 décimales (~1 km, assez pour une carte du monde). Source : GeoNames, fichier public
// cities1000 (https://download.geonames.org/export/dump/, licence CC BY 4.0), relevé en septembre 2026.

export const CONTINENTS = Object.freeze([
  'Afrique',
  'Amérique du Nord',
  'Amérique du Sud',
  'Asie',
  'Europe',
  'Océanie',
]);

const capitales = [
  // Afrique (54)
  { pays: 'Afrique du Sud', capitale: 'Pretoria', continent: 'Afrique', fuseau: 'Africa/Johannesburg', lat: -25.74, lon: 28.19, autresCapitales: ['Le Cap', 'Bloemfontein'] },
  { pays: 'Algérie', capitale: 'Alger', continent: 'Afrique', fuseau: 'Africa/Algiers', lat: 36.73, lon: 3.09 },
  { pays: 'Angola', capitale: 'Luanda', continent: 'Afrique', fuseau: 'Africa/Luanda', lat: -8.84, lon: 13.23 },
  { pays: 'Bénin', capitale: 'Porto-Novo', continent: 'Afrique', fuseau: 'Africa/Porto-Novo', lat: 6.5, lon: 2.6, autresCapitales: ['Cotonou'] },
  { pays: 'Botswana', capitale: 'Gaborone', continent: 'Afrique', fuseau: 'Africa/Gaborone', lat: -24.65, lon: 25.91 },
  { pays: 'Burkina Faso', capitale: 'Ouagadougou', continent: 'Afrique', fuseau: 'Africa/Ouagadougou', lat: 12.37, lon: -1.53 },
  { pays: 'Burundi', capitale: 'Gitega', continent: 'Afrique', fuseau: 'Africa/Bujumbura', lat: -3.43, lon: 29.92, autresCapitales: ['Bujumbura'] },
  { pays: 'Cap-Vert', capitale: 'Praia', continent: 'Afrique', fuseau: 'Atlantic/Cape_Verde', lat: 14.93, lon: -23.51 },
  { pays: 'Cameroun', capitale: 'Yaoundé', continent: 'Afrique', fuseau: 'Africa/Douala', lat: 3.87, lon: 11.52 },
  { pays: 'Centrafrique', capitale: 'Bangui', continent: 'Afrique', fuseau: 'Africa/Bangui', lat: 4.36, lon: 18.55 },
  { pays: 'Comores', capitale: 'Moroni', continent: 'Afrique', fuseau: 'Indian/Comoro', lat: -11.7, lon: 43.26 },
  { pays: 'Congo', capitale: 'Brazzaville', continent: 'Afrique', fuseau: 'Africa/Brazzaville', lat: -4.27, lon: 15.28 },
  { pays: 'République démocratique du Congo', capitale: 'Kinshasa', continent: 'Afrique', fuseau: 'Africa/Kinshasa', lat: -4.33, lon: 15.31 },
  { pays: "Côte d'Ivoire", capitale: 'Yamoussoukro', continent: 'Afrique', fuseau: 'Africa/Abidjan', lat: 6.82, lon: -5.28, autresCapitales: ['Abidjan'] },
  { pays: 'Djibouti', capitale: 'Djibouti', continent: 'Afrique', fuseau: 'Africa/Djibouti', lat: 11.59, lon: 43.15 },
  { pays: 'Égypte', capitale: 'Le Caire', continent: 'Afrique', fuseau: 'Africa/Cairo', lat: 30.06, lon: 31.25 },
  { pays: 'Érythrée', capitale: 'Asmara', continent: 'Afrique', fuseau: 'Africa/Asmara', lat: 15.34, lon: 38.93 },
  { pays: 'Eswatini', capitale: 'Mbabane', continent: 'Afrique', fuseau: 'Africa/Mbabane', lat: -26.32, lon: 31.13, autresCapitales: ['Lobamba'] },
  { pays: 'Éthiopie', capitale: 'Addis-Abeba', continent: 'Afrique', fuseau: 'Africa/Addis_Ababa', lat: 9.02, lon: 38.75 },
  { pays: 'Gabon', capitale: 'Libreville', continent: 'Afrique', fuseau: 'Africa/Libreville', lat: 0.39, lon: 9.45 },
  { pays: 'Gambie', capitale: 'Banjul', continent: 'Afrique', fuseau: 'Africa/Banjul', lat: 13.45, lon: -16.58 },
  { pays: 'Ghana', capitale: 'Accra', continent: 'Afrique', fuseau: 'Africa/Accra', lat: 5.56, lon: -0.2 },
  { pays: 'Guinée', capitale: 'Conakry', continent: 'Afrique', fuseau: 'Africa/Conakry', lat: 9.54, lon: -13.68 },
  { pays: 'Guinée-Bissau', capitale: 'Bissau', continent: 'Afrique', fuseau: 'Africa/Bissau', lat: 11.86, lon: -15.6 },
  { pays: 'Guinée équatoriale', capitale: 'Malabo', continent: 'Afrique', fuseau: 'Africa/Malabo', lat: 3.76, lon: 8.78 },
  { pays: 'Kenya', capitale: 'Nairobi', continent: 'Afrique', fuseau: 'Africa/Nairobi', lat: -1.28, lon: 36.82 },
  { pays: 'Lesotho', capitale: 'Maseru', continent: 'Afrique', fuseau: 'Africa/Maseru', lat: -29.32, lon: 27.48 },
  { pays: 'Liberia', capitale: 'Monrovia', continent: 'Afrique', fuseau: 'Africa/Monrovia', lat: 6.3, lon: -10.8 },
  { pays: 'Libye', capitale: 'Tripoli', continent: 'Afrique', fuseau: 'Africa/Tripoli', lat: 32.89, lon: 13.19 },
  { pays: 'Madagascar', capitale: 'Antananarivo', continent: 'Afrique', fuseau: 'Indian/Antananarivo', lat: -18.91, lon: 47.54 },
  { pays: 'Malawi', capitale: 'Lilongwe', continent: 'Afrique', fuseau: 'Africa/Blantyre', lat: -13.97, lon: 33.79 },
  { pays: 'Mali', capitale: 'Bamako', continent: 'Afrique', fuseau: 'Africa/Bamako', lat: 12.61, lon: -7.98 },
  { pays: 'Maroc', capitale: 'Rabat', continent: 'Afrique', fuseau: 'Africa/Casablanca', lat: 34.01, lon: -6.83 },
  { pays: 'Maurice', capitale: 'Port-Louis', continent: 'Afrique', fuseau: 'Indian/Mauritius', lat: -20.16, lon: 57.5 },
  { pays: 'Mauritanie', capitale: 'Nouakchott', continent: 'Afrique', fuseau: 'Africa/Nouakchott', lat: 18.09, lon: -15.98 },
  { pays: 'Mozambique', capitale: 'Maputo', continent: 'Afrique', fuseau: 'Africa/Maputo', lat: -25.97, lon: 32.58 },
  { pays: 'Namibie', capitale: 'Windhoek', continent: 'Afrique', fuseau: 'Africa/Windhoek', lat: -22.56, lon: 17.08 },
  { pays: 'Niger', capitale: 'Niamey', continent: 'Afrique', fuseau: 'Africa/Niamey', lat: 13.51, lon: 2.11 },
  { pays: 'Nigeria', capitale: 'Abuja', continent: 'Afrique', fuseau: 'Africa/Lagos', lat: 9.06, lon: 7.5 },
  { pays: 'Ouganda', capitale: 'Kampala', continent: 'Afrique', fuseau: 'Africa/Kampala', lat: 0.32, lon: 32.58 },
  { pays: 'Rwanda', capitale: 'Kigali', continent: 'Afrique', fuseau: 'Africa/Kigali', lat: -1.95, lon: 30.06 },
  { pays: 'Sao Tomé-et-Principe', capitale: 'São Tomé', continent: 'Afrique', fuseau: 'Africa/Sao_Tome', lat: 0.34, lon: 6.73 },
  { pays: 'Sénégal', capitale: 'Dakar', continent: 'Afrique', fuseau: 'Africa/Dakar', lat: 14.69, lon: -17.44 },
  { pays: 'Seychelles', capitale: 'Victoria', continent: 'Afrique', fuseau: 'Indian/Mahe', lat: -4.62, lon: 55.46 },
  { pays: 'Sierra Leone', capitale: 'Freetown', continent: 'Afrique', fuseau: 'Africa/Freetown', lat: 8.49, lon: -13.24 },
  { pays: 'Somalie', capitale: 'Mogadiscio', continent: 'Afrique', fuseau: 'Africa/Mogadishu', lat: 2.04, lon: 45.34 },
  { pays: 'Soudan', capitale: 'Khartoum', continent: 'Afrique', fuseau: 'Africa/Khartoum', lat: 15.55, lon: 32.53 },
  { pays: 'Soudan du Sud', capitale: 'Djouba', continent: 'Afrique', fuseau: 'Africa/Juba', lat: 4.85, lon: 31.58 },
  { pays: 'Tanzanie', capitale: 'Dodoma', continent: 'Afrique', fuseau: 'Africa/Dar_es_Salaam', lat: -6.17, lon: 35.74, autresCapitales: ['Dar es Salam'] },
  { pays: 'Tchad', capitale: "N'Djaména", continent: 'Afrique', fuseau: 'Africa/Ndjamena', lat: 12.11, lon: 15.04 },
  { pays: 'Togo', capitale: 'Lomé', continent: 'Afrique', fuseau: 'Africa/Lome', lat: 6.13, lon: 1.22 },
  { pays: 'Tunisie', capitale: 'Tunis', continent: 'Afrique', fuseau: 'Africa/Tunis', lat: 36.82, lon: 10.17 },
  { pays: 'Zambie', capitale: 'Lusaka', continent: 'Afrique', fuseau: 'Africa/Lusaka', lat: -15.41, lon: 28.29 },
  { pays: 'Zimbabwe', capitale: 'Harare', continent: 'Afrique', fuseau: 'Africa/Harare', lat: -17.83, lon: 31.05 },

  // Amérique du Nord, Amérique centrale et Caraïbes (23)
  { pays: 'Antigua-et-Barbuda', capitale: "Saint John's", continent: 'Amérique du Nord', fuseau: 'America/Antigua', lat: 17.12, lon: -61.84 },
  { pays: 'Bahamas', capitale: 'Nassau', continent: 'Amérique du Nord', fuseau: 'America/Nassau', lat: 25.06, lon: -77.34 },
  { pays: 'Barbade', capitale: 'Bridgetown', continent: 'Amérique du Nord', fuseau: 'America/Barbados', lat: 13.11, lon: -59.62 },
  { pays: 'Belize', capitale: 'Belmopan', continent: 'Amérique du Nord', fuseau: 'America/Belize', lat: 17.25, lon: -88.76 },
  { pays: 'Canada', capitale: 'Ottawa', continent: 'Amérique du Nord', fuseau: 'America/Toronto', lat: 45.41, lon: -75.7 },
  { pays: 'Costa Rica', capitale: 'San José', continent: 'Amérique du Nord', fuseau: 'America/Costa_Rica', lat: 9.93, lon: -84.08 },
  { pays: 'Cuba', capitale: 'La Havane', continent: 'Amérique du Nord', fuseau: 'America/Havana', lat: 23.13, lon: -82.38 },
  { pays: 'Dominique', capitale: 'Roseau', continent: 'Amérique du Nord', fuseau: 'America/Dominica', lat: 15.3, lon: -61.39 },
  { pays: 'États-Unis', capitale: 'Washington', continent: 'Amérique du Nord', fuseau: 'America/New_York', lat: 38.9, lon: -77.04 },
  { pays: 'Grenade', capitale: 'Saint-Georges', continent: 'Amérique du Nord', fuseau: 'America/Grenada', lat: 12.05, lon: -61.75 },
  { pays: 'Guatemala', capitale: 'Guatemala', continent: 'Amérique du Nord', fuseau: 'America/Guatemala', lat: 14.64, lon: -90.51 },
  { pays: 'Haïti', capitale: 'Port-au-Prince', continent: 'Amérique du Nord', fuseau: 'America/Port-au-Prince', lat: 18.54, lon: -72.34 },
  { pays: 'Honduras', capitale: 'Tegucigalpa', continent: 'Amérique du Nord', fuseau: 'America/Tegucigalpa', lat: 14.08, lon: -87.21 },
  { pays: 'Jamaïque', capitale: 'Kingston', continent: 'Amérique du Nord', fuseau: 'America/Jamaica', lat: 18, lon: -76.79 },
  { pays: 'Mexique', capitale: 'Mexico', continent: 'Amérique du Nord', fuseau: 'America/Mexico_City', lat: 19.43, lon: -99.13 },
  { pays: 'Nicaragua', capitale: 'Managua', continent: 'Amérique du Nord', fuseau: 'America/Managua', lat: 12.13, lon: -86.25 },
  { pays: 'Panama', capitale: 'Panama', continent: 'Amérique du Nord', fuseau: 'America/Panama', lat: 8.99, lon: -79.52 },
  { pays: 'République dominicaine', capitale: 'Saint-Domingue', continent: 'Amérique du Nord', fuseau: 'America/Santo_Domingo', lat: 18.47, lon: -69.89 },
  { pays: 'Saint-Christophe-et-Niévès', capitale: 'Basseterre', continent: 'Amérique du Nord', fuseau: 'America/St_Kitts', lat: 17.3, lon: -62.72 },
  { pays: 'Sainte-Lucie', capitale: 'Castries', continent: 'Amérique du Nord', fuseau: 'America/St_Lucia', lat: 14, lon: -61.01 },
  { pays: 'Saint-Vincent-et-les-Grenadines', capitale: 'Kingstown', continent: 'Amérique du Nord', fuseau: 'America/St_Vincent', lat: 13.16, lon: -61.23 },
  { pays: 'Salvador', capitale: 'San Salvador', continent: 'Amérique du Nord', fuseau: 'America/El_Salvador', lat: 13.69, lon: -89.19 },
  { pays: 'Trinité-et-Tobago', capitale: "Port-d'Espagne", continent: 'Amérique du Nord', fuseau: 'America/Port_of_Spain', lat: 10.67, lon: -61.52 },

  // Amérique du Sud (12)
  { pays: 'Argentine', capitale: 'Buenos Aires', continent: 'Amérique du Sud', fuseau: 'America/Argentina/Buenos_Aires', lat: -34.61, lon: -58.38 },
  { pays: 'Bolivie', capitale: 'Sucre', continent: 'Amérique du Sud', fuseau: 'America/La_Paz', lat: -19.03, lon: -65.26, autresCapitales: ['La Paz'] },
  { pays: 'Brésil', capitale: 'Brasilia', continent: 'Amérique du Sud', fuseau: 'America/Sao_Paulo', lat: -15.78, lon: -47.93 },
  { pays: 'Chili', capitale: 'Santiago', continent: 'Amérique du Sud', fuseau: 'America/Santiago', lat: -33.46, lon: -70.65 },
  { pays: 'Colombie', capitale: 'Bogota', continent: 'Amérique du Sud', fuseau: 'America/Bogota', lat: 4.61, lon: -74.08 },
  { pays: 'Équateur', capitale: 'Quito', continent: 'Amérique du Sud', fuseau: 'America/Guayaquil', lat: -0.23, lon: -78.52 },
  { pays: 'Guyana', capitale: 'Georgetown', continent: 'Amérique du Sud', fuseau: 'America/Guyana', lat: 6.8, lon: -58.16 },
  { pays: 'Paraguay', capitale: 'Asuncion', continent: 'Amérique du Sud', fuseau: 'America/Asuncion', lat: -25.29, lon: -57.65 },
  { pays: 'Pérou', capitale: 'Lima', continent: 'Amérique du Sud', fuseau: 'America/Lima', lat: -12.04, lon: -77.03 },
  { pays: 'Suriname', capitale: 'Paramaribo', continent: 'Amérique du Sud', fuseau: 'America/Paramaribo', lat: 5.87, lon: -55.17 },
  { pays: 'Uruguay', capitale: 'Montevideo', continent: 'Amérique du Sud', fuseau: 'America/Montevideo', lat: -34.9, lon: -56.19 },
  { pays: 'Venezuela', capitale: 'Caracas', continent: 'Amérique du Sud', fuseau: 'America/Caracas', lat: 10.49, lon: -66.88 },

  // Asie (48)
  { pays: 'Afghanistan', capitale: 'Kaboul', continent: 'Asie', fuseau: 'Asia/Kabul', lat: 34.53, lon: 69.17 },
  { pays: 'Arabie saoudite', capitale: 'Riyad', continent: 'Asie', fuseau: 'Asia/Riyadh', lat: 24.69, lon: 46.72 },
  { pays: 'Arménie', capitale: 'Erevan', continent: 'Asie', fuseau: 'Asia/Yerevan', lat: 40.18, lon: 44.51 },
  { pays: 'Azerbaïdjan', capitale: 'Bakou', continent: 'Asie', fuseau: 'Asia/Baku', lat: 40.38, lon: 49.89 },
  { pays: 'Bahreïn', capitale: 'Manama', continent: 'Asie', fuseau: 'Asia/Bahrain', lat: 26.23, lon: 50.59 },
  { pays: 'Bangladesh', capitale: 'Dacca', continent: 'Asie', fuseau: 'Asia/Dhaka', lat: 23.71, lon: 90.41 },
  { pays: 'Bhoutan', capitale: 'Thimphou', continent: 'Asie', fuseau: 'Asia/Thimphu', lat: 27.47, lon: 89.64 },
  { pays: 'Birmanie', capitale: 'Naypyidaw', continent: 'Asie', fuseau: 'Asia/Yangon', lat: 19.75, lon: 96.13 },
  { pays: 'Brunei', capitale: 'Bandar Seri Begawan', continent: 'Asie', fuseau: 'Asia/Brunei', lat: 4.89, lon: 114.94 },
  { pays: 'Cambodge', capitale: 'Phnom Penh', continent: 'Asie', fuseau: 'Asia/Phnom_Penh', lat: 11.56, lon: 104.92 },
  { pays: 'Chine', capitale: 'Pékin', continent: 'Asie', fuseau: 'Asia/Shanghai', lat: 39.91, lon: 116.4 },
  { pays: 'Chypre', capitale: 'Nicosie', continent: 'Asie', fuseau: 'Asia/Nicosia', lat: 35.17, lon: 33.35 },
  { pays: 'Corée du Nord', capitale: 'Pyongyang', continent: 'Asie', fuseau: 'Asia/Pyongyang', lat: 39.03, lon: 125.75 },
  { pays: 'Corée du Sud', capitale: 'Séoul', continent: 'Asie', fuseau: 'Asia/Seoul', lat: 37.57, lon: 126.98 },
  { pays: 'Émirats arabes unis', capitale: 'Abou Dabi', continent: 'Asie', fuseau: 'Asia/Dubai', lat: 24.45, lon: 54.4 },
  { pays: 'Géorgie', capitale: 'Tbilissi', continent: 'Asie', fuseau: 'Asia/Tbilisi', lat: 41.69, lon: 44.83 },
  { pays: 'Inde', capitale: 'New Delhi', continent: 'Asie', fuseau: 'Asia/Kolkata', lat: 28.62, lon: 77.21 },
  { pays: 'Indonésie', capitale: 'Jakarta', continent: 'Asie', fuseau: 'Asia/Jakarta', lat: -6.21, lon: 106.85 },
  { pays: 'Irak', capitale: 'Bagdad', continent: 'Asie', fuseau: 'Asia/Baghdad', lat: 33.34, lon: 44.4 },
  { pays: 'Iran', capitale: 'Téhéran', continent: 'Asie', fuseau: 'Asia/Tehran', lat: 35.69, lon: 51.42 },
  { pays: 'Israël', capitale: 'Jérusalem', continent: 'Asie', fuseau: 'Asia/Jerusalem', lat: 31.77, lon: 35.22 },
  { pays: 'Japon', capitale: 'Tokyo', continent: 'Asie', fuseau: 'Asia/Tokyo', lat: 35.69, lon: 139.69 },
  { pays: 'Jordanie', capitale: 'Amman', continent: 'Asie', fuseau: 'Asia/Amman', lat: 31.96, lon: 35.95 },
  { pays: 'Kazakhstan', capitale: 'Astana', continent: 'Asie', fuseau: 'Asia/Almaty', lat: 51.18, lon: 71.45 },
  { pays: 'Kirghizistan', capitale: 'Bichkek', continent: 'Asie', fuseau: 'Asia/Bishkek', lat: 42.87, lon: 74.59 },
  { pays: 'Koweït', capitale: 'Koweït', continent: 'Asie', fuseau: 'Asia/Kuwait', lat: 29.37, lon: 47.97 },
  { pays: 'Laos', capitale: 'Vientiane', continent: 'Asie', fuseau: 'Asia/Vientiane', lat: 17.97, lon: 102.6 },
  { pays: 'Liban', capitale: 'Beyrouth', continent: 'Asie', fuseau: 'Asia/Beirut', lat: 33.89, lon: 35.5 },
  { pays: 'Malaisie', capitale: 'Kuala Lumpur', continent: 'Asie', fuseau: 'Asia/Kuala_Lumpur', lat: 3.14, lon: 101.69, autresCapitales: ['Putrajaya'] },
  { pays: 'Maldives', capitale: 'Malé', continent: 'Asie', fuseau: 'Indian/Maldives', lat: 4.18, lon: 73.51 },
  { pays: 'Mongolie', capitale: 'Oulan-Bator', continent: 'Asie', fuseau: 'Asia/Ulaanbaatar', lat: 47.91, lon: 106.88 },
  { pays: 'Népal', capitale: 'Katmandou', continent: 'Asie', fuseau: 'Asia/Kathmandu', lat: 27.7, lon: 85.32 },
  { pays: 'Oman', capitale: 'Mascate', continent: 'Asie', fuseau: 'Asia/Muscat', lat: 23.58, lon: 58.41 },
  { pays: 'Ouzbékistan', capitale: 'Tachkent', continent: 'Asie', fuseau: 'Asia/Tashkent', lat: 41.26, lon: 69.22 },
  { pays: 'Pakistan', capitale: 'Islamabad', continent: 'Asie', fuseau: 'Asia/Karachi', lat: 33.72, lon: 73.04 },
  { pays: 'Palestine', capitale: 'Ramallah', continent: 'Asie', fuseau: 'Asia/Hebron', lat: 31.9, lon: 35.2, autresCapitales: ['Jérusalem-Est'] },
  { pays: 'Philippines', capitale: 'Manille', continent: 'Asie', fuseau: 'Asia/Manila', lat: 14.6, lon: 120.98 },
  { pays: 'Qatar', capitale: 'Doha', continent: 'Asie', fuseau: 'Asia/Qatar', lat: 25.29, lon: 51.53 },
  { pays: 'Singapour', capitale: 'Singapour', continent: 'Asie', fuseau: 'Asia/Singapore', lat: 1.29, lon: 103.85 },
  { pays: 'Sri Lanka', capitale: 'Sri Jayawardenepura Kotte', continent: 'Asie', fuseau: 'Asia/Colombo', lat: 6.88, lon: 79.91, autresCapitales: ['Colombo'] },
  { pays: 'Syrie', capitale: 'Damas', continent: 'Asie', fuseau: 'Asia/Damascus', lat: 33.51, lon: 36.29 },
  { pays: 'Tadjikistan', capitale: 'Douchanbé', continent: 'Asie', fuseau: 'Asia/Dushanbe', lat: 38.54, lon: 68.78 },
  { pays: 'Thaïlande', capitale: 'Bangkok', continent: 'Asie', fuseau: 'Asia/Bangkok', lat: 13.75, lon: 100.5 },
  { pays: 'Timor oriental', capitale: 'Dili', continent: 'Asie', fuseau: 'Asia/Dili', lat: -8.56, lon: 125.57 },
  { pays: 'Turkménistan', capitale: 'Achgabat', continent: 'Asie', fuseau: 'Asia/Ashgabat', lat: 37.95, lon: 58.38 },
  { pays: 'Turquie', capitale: 'Ankara', continent: 'Asie', fuseau: 'Europe/Istanbul', lat: 39.92, lon: 32.85 },
  { pays: 'Viêt Nam', capitale: 'Hanoï', continent: 'Asie', fuseau: 'Asia/Ho_Chi_Minh', lat: 21.02, lon: 105.84 },
  { pays: 'Yémen', capitale: 'Sanaa', continent: 'Asie', fuseau: 'Asia/Aden', lat: 15.35, lon: 44.21 },

  // Europe (44)
  { pays: 'Albanie', capitale: 'Tirana', continent: 'Europe', fuseau: 'Europe/Tirane', lat: 41.33, lon: 19.82 },
  { pays: 'Allemagne', capitale: 'Berlin', continent: 'Europe', fuseau: 'Europe/Berlin', lat: 52.52, lon: 13.41 },
  { pays: 'Andorre', capitale: 'Andorre-la-Vieille', continent: 'Europe', fuseau: 'Europe/Andorra', lat: 42.51, lon: 1.52 },
  { pays: 'Autriche', capitale: 'Vienne', continent: 'Europe', fuseau: 'Europe/Vienna', lat: 48.21, lon: 16.37 },
  { pays: 'Belgique', capitale: 'Bruxelles', continent: 'Europe', fuseau: 'Europe/Brussels', lat: 50.85, lon: 4.35 },
  { pays: 'Biélorussie', capitale: 'Minsk', continent: 'Europe', fuseau: 'Europe/Minsk', lat: 53.9, lon: 27.57 },
  { pays: 'Bosnie-Herzégovine', capitale: 'Sarajevo', continent: 'Europe', fuseau: 'Europe/Sarajevo', lat: 43.85, lon: 18.36 },
  { pays: 'Bulgarie', capitale: 'Sofia', continent: 'Europe', fuseau: 'Europe/Sofia', lat: 42.7, lon: 23.32 },
  { pays: 'Croatie', capitale: 'Zagreb', continent: 'Europe', fuseau: 'Europe/Zagreb', lat: 45.81, lon: 15.98 },
  { pays: 'Danemark', capitale: 'Copenhague', continent: 'Europe', fuseau: 'Europe/Copenhagen', lat: 55.68, lon: 12.57 },
  { pays: 'Espagne', capitale: 'Madrid', continent: 'Europe', fuseau: 'Europe/Madrid', lat: 40.42, lon: -3.7 },
  { pays: 'Estonie', capitale: 'Tallinn', continent: 'Europe', fuseau: 'Europe/Tallinn', lat: 59.44, lon: 24.75 },
  { pays: 'Finlande', capitale: 'Helsinki', continent: 'Europe', fuseau: 'Europe/Helsinki', lat: 60.17, lon: 24.94 },
  { pays: 'France', capitale: 'Paris', continent: 'Europe', fuseau: 'Europe/Paris', lat: 48.85, lon: 2.35 },
  { pays: 'Grèce', capitale: 'Athènes', continent: 'Europe', fuseau: 'Europe/Athens', lat: 37.98, lon: 23.73 },
  { pays: 'Hongrie', capitale: 'Budapest', continent: 'Europe', fuseau: 'Europe/Budapest', lat: 47.5, lon: 19.04 },
  { pays: 'Irlande', capitale: 'Dublin', continent: 'Europe', fuseau: 'Europe/Dublin', lat: 53.33, lon: -6.25 },
  { pays: 'Islande', capitale: 'Reykjavik', continent: 'Europe', fuseau: 'Atlantic/Reykjavik', lat: 64.14, lon: -21.9 },
  { pays: 'Italie', capitale: 'Rome', continent: 'Europe', fuseau: 'Europe/Rome', lat: 41.89, lon: 12.51 },
  { pays: 'Lettonie', capitale: 'Riga', continent: 'Europe', fuseau: 'Europe/Riga', lat: 56.95, lon: 24.11 },
  { pays: 'Liechtenstein', capitale: 'Vaduz', continent: 'Europe', fuseau: 'Europe/Vaduz', lat: 47.14, lon: 9.52 },
  { pays: 'Lituanie', capitale: 'Vilnius', continent: 'Europe', fuseau: 'Europe/Vilnius', lat: 54.69, lon: 25.28 },
  { pays: 'Luxembourg', capitale: 'Luxembourg', continent: 'Europe', fuseau: 'Europe/Luxembourg', lat: 49.61, lon: 6.13 },
  { pays: 'Macédoine du Nord', capitale: 'Skopje', continent: 'Europe', fuseau: 'Europe/Skopje', lat: 42, lon: 21.43 },
  { pays: 'Malte', capitale: 'La Valette', continent: 'Europe', fuseau: 'Europe/Malta', lat: 35.9, lon: 14.51 },
  { pays: 'Moldavie', capitale: 'Chișinău', continent: 'Europe', fuseau: 'Europe/Chisinau', lat: 47.01, lon: 28.86 },
  { pays: 'Monaco', capitale: 'Monaco', continent: 'Europe', fuseau: 'Europe/Monaco', lat: 43.74, lon: 7.42 },
  { pays: 'Monténégro', capitale: 'Podgorica', continent: 'Europe', fuseau: 'Europe/Podgorica', lat: 42.44, lon: 19.26 },
  { pays: 'Norvège', capitale: 'Oslo', continent: 'Europe', fuseau: 'Europe/Oslo', lat: 59.91, lon: 10.75 },
  { pays: 'Pays-Bas', capitale: 'Amsterdam', continent: 'Europe', fuseau: 'Europe/Amsterdam', lat: 52.37, lon: 4.89, autresCapitales: ['La Haye'] },
  { pays: 'Pologne', capitale: 'Varsovie', continent: 'Europe', fuseau: 'Europe/Warsaw', lat: 52.23, lon: 21.01 },
  { pays: 'Portugal', capitale: 'Lisbonne', continent: 'Europe', fuseau: 'Europe/Lisbon', lat: 38.73, lon: -9.15 },
  { pays: 'Roumanie', capitale: 'Bucarest', continent: 'Europe', fuseau: 'Europe/Bucharest', lat: 44.43, lon: 26.11 },
  { pays: 'Royaume-Uni', capitale: 'Londres', continent: 'Europe', fuseau: 'Europe/London', lat: 51.51, lon: -0.13 },
  { pays: 'Russie', capitale: 'Moscou', continent: 'Europe', fuseau: 'Europe/Moscow', lat: 55.75, lon: 37.62 },
  { pays: 'Saint-Marin', capitale: 'Saint-Marin', continent: 'Europe', fuseau: 'Europe/San_Marino', lat: 43.94, lon: 12.45 },
  { pays: 'Serbie', capitale: 'Belgrade', continent: 'Europe', fuseau: 'Europe/Belgrade', lat: 44.8, lon: 20.47 },
  { pays: 'Slovaquie', capitale: 'Bratislava', continent: 'Europe', fuseau: 'Europe/Bratislava', lat: 48.15, lon: 17.11 },
  { pays: 'Slovénie', capitale: 'Ljubljana', continent: 'Europe', fuseau: 'Europe/Ljubljana', lat: 46.05, lon: 14.51 },
  { pays: 'Suède', capitale: 'Stockholm', continent: 'Europe', fuseau: 'Europe/Stockholm', lat: 59.33, lon: 18.07 },
  { pays: 'Suisse', capitale: 'Berne', continent: 'Europe', fuseau: 'Europe/Zurich', lat: 46.95, lon: 7.45 },
  { pays: 'Tchéquie', capitale: 'Prague', continent: 'Europe', fuseau: 'Europe/Prague', lat: 50.09, lon: 14.42 },
  { pays: 'Ukraine', capitale: 'Kiev', continent: 'Europe', fuseau: 'Europe/Kyiv', lat: 50.45, lon: 30.52 },
  { pays: 'Vatican', capitale: 'Cité du Vatican', continent: 'Europe', fuseau: 'Europe/Vatican', lat: 41.9, lon: 12.45 },

  // Océanie (14)
  { pays: 'Australie', capitale: 'Canberra', continent: 'Océanie', fuseau: 'Australia/Sydney', lat: -35.28, lon: 149.13 },
  { pays: 'Fidji', capitale: 'Suva', continent: 'Océanie', fuseau: 'Pacific/Fiji', lat: -18.14, lon: 178.43 },
  { pays: 'Kiribati', capitale: 'Tarawa-Sud', continent: 'Océanie', fuseau: 'Pacific/Tarawa', lat: 1.33, lon: 172.98 },
  { pays: 'Îles Marshall', capitale: 'Majuro', continent: 'Océanie', fuseau: 'Pacific/Majuro', lat: 7.09, lon: 171.38 },
  { pays: 'Micronésie', capitale: 'Palikir', continent: 'Océanie', fuseau: 'Pacific/Pohnpei', lat: 6.92, lon: 158.16 },
  { pays: 'Nauru', capitale: 'Yaren', continent: 'Océanie', fuseau: 'Pacific/Nauru', lat: -0.55, lon: 166.93 },
  { pays: 'Nouvelle-Zélande', capitale: 'Wellington', continent: 'Océanie', fuseau: 'Pacific/Auckland', lat: -41.29, lon: 174.78 },
  { pays: 'Palaos', capitale: 'Ngerulmud', continent: 'Océanie', fuseau: 'Pacific/Palau', lat: 7.5, lon: 134.62 },
  { pays: 'Papouasie-Nouvelle-Guinée', capitale: 'Port Moresby', continent: 'Océanie', fuseau: 'Pacific/Port_Moresby', lat: -9.48, lon: 147.15 },
  { pays: 'Îles Salomon', capitale: 'Honiara', continent: 'Océanie', fuseau: 'Pacific/Guadalcanal', lat: -9.43, lon: 159.95 },
  { pays: 'Samoa', capitale: 'Apia', continent: 'Océanie', fuseau: 'Pacific/Apia', lat: -13.83, lon: -171.77 },
  { pays: 'Tonga', capitale: 'Nukuʻalofa', continent: 'Océanie', fuseau: 'Pacific/Tongatapu', lat: -21.14, lon: -175.2 },
  { pays: 'Tuvalu', capitale: 'Funafuti', continent: 'Océanie', fuseau: 'Pacific/Funafuti', lat: -8.52, lon: 179.19 },
  { pays: 'Vanuatu', capitale: 'Port-Vila', continent: 'Océanie', fuseau: 'Pacific/Efate', lat: -17.74, lon: 168.31 },
];

// Figées en profondeur : un module qui les lit ne peut pas les modifier par mégarde.
for (const entree of capitales) {
  if (entree.autresCapitales) Object.freeze(entree.autresCapitales);
  Object.freeze(entree);
}

export const CAPITALES = Object.freeze(capitales);
